In [7]:
import numpy as np

In [8]:
np.random.seed(5)
z_1 = 10*np.random.rand(5, 1)-5
z_1

array([[-2.78006829],
       [ 3.70732306],
       [-2.93280845],
       [ 4.18610908],
       [-0.11588811]])

In [9]:
h = z_1.copy()
h[h < 0] = 0
h

array([[0.        ],
       [3.70732306],
       [0.        ],
       [4.18610908],
       [0.        ]])

In [10]:
def relu(z):
    out = z.copy()
    out[out<0]=0
    return out

In [11]:
z = np.array([[-1.25459881], [ 4.50714306], [ 2.31993942], [ 0.98658484], [-3.4398136 ]])
relu(z)

array([[0.        ],
       [4.50714306],
       [2.31993942],
       [0.98658484],
       [0.        ]])

In [12]:
z = np.array([9, 8, 11, 10, 8.5])
z

array([ 9. ,  8. , 11. , 10. ,  8.5])

In [13]:
e_z = np.exp(z)
e_z

array([ 8103.08392758,  2980.95798704, 59874.1417152 , 22026.46579481,
        4914.7688403 ])

In [14]:
sum_ez = np.sum(e_z)
sum_ez

97899.41826492078

In [17]:
y_hat = e_z/sum_ez
y_hat

array([0.08276948, 0.03044919, 0.61158833, 0.22499077, 0.05020223])

In [16]:
def softmax(z):
    e_z = np.exp(z)
    sum_e_z = np.sum(e_z)
    return e_z / sum_e_z

In [18]:
softmax([9, 8, 11, 10, 8.5])

array([0.08276948, 0.03044919, 0.61158833, 0.22499077, 0.05020223])

In [19]:
assert np.sum(softmax([9, 8, 11, 10, 8.5])) == 1

In [21]:
V = 5
x_array = np.zeros(V)
x_array.shape

(5,)

In [25]:
x_column_vector = x_array.copy()
x_column_vector.shape = (V, 1)
x_column_vector.shape

(5, 1)